grammarDict = {'PASTPAST': 'ruru',
               'PAST'    : 'ru',
               'PASTFUT' : 'rumo',
               'FUTPAST' : 'moru',
               'FUT'     : 'mo',
               'FUTFUT'  : 'momo',
               'PASTPASTPROG': 'ruruku',
               'PASTPROG'    : 'ruku',
               'PASTFUTPROG' : 'rumoku',
               'PRESPROG'    : 'ku',
               'FUTPASTPROG' : 'moruku',
               'FUTPROG'     : 'moku',
               'FUTFUTPROG'  : 'moonku',
               'SING1st': 'ka',
               'SING2nd': 'du',
               'SING3rd': 'ha',
               'PLUR1st': 'kang',
               'PLUR2nd': 'dun',
               'PLUR3rd': 'han',
               'ACC': 'u',
               'DAT': 'i',
               'GEN': 'o',
               'PLURAL': 'n'}
